# Site settings
title: The Personal Website of John Smith
email: webmaster@johnsmith.site
description: >- # this means to ignore newlines until "baseurl:"
  The personal website and blog of Mr. John Smith.
baseurl: ""
url: "" # http://example.com
twitter_username: palaces_of_gold
github_username:  theinvertedform
permalink: /:year/:month/:title

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives

# Collections
collections:
    authors:
      output: true

# Arhives
jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Minima
header_pages:
  - about.md
  - blog.md
  - archive.md

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
