# Site settings
title: The North Star
email: northstar@northstarmag.com
description: >- # this means to ignore newlines until "baseurl:"
  A new media going against the grain of the corporate press and the elites.
baseurl: ""
url: "" # http://example.com
twitter_username: NewsNorthstar
github_username:  theinvertedform

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
    authors:
      output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"


exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
