# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: 'editorial_workflow'
media_folder: 'assets/img'

collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    fields:
      - { name: Title }
      - { name: Author }
